### ISSUE TITLE
本日学習したことについて

### ISSUE THREAD

**Issue by morimotoyuuki111** [morimotoyuuki111/gin#1]
# ginの環境構築について
# 質問1
簡単な環境構築を試してみましたが<br>
ginもWebアプリを作成する際に<br>
- Xcode Command Line Tools
- Homebrew
- tree
- direnv
- Go
- MySQL
の環境構築が必要になってきますか？<br>
# 質問2
環境構築は案件によって違いますか？

# 質問３
```go
package main

import "github.com/gin-gonic/gin"

import "net/http"

func main() {
    engine:= gin.Default()
    engine.GET("/", func(c *gin.Context) {
        c.JSON(http.StatusOK, gin.H{
            "message": "hello world",
        })
    })
    engine.Run(":3000")
}
```
上記のコードの
```go
"github.com/gin-gonic/gin"
```
はパッケージですか？

# 質問４
ginの機能はどのように理解すれば良いですか？
```go
Gin v1 の安定性
ヒープメモリの拡張が0のルーター

最速の http ルーターとフレームワーク

一揃いのユニットテストをすべて満たしている

バトルがテストされている

APIは固まっており、新しいバージョンが既存のコードを壊すことはない
```

# 質問５
Jsoniterはどう理解すれば良いですか？

**Comment by totsumaru** [comment]
## 質問1

最低限必要なのは次の2つです。
- Go
- MySQL

そのほかはオプションですが、
- Xcode Command Line Tools
は必要ないかなと思います。
（treeやbrewは便利なので使えばOKかなと思います）

## 質問2

環境はPCによって違います。
会社がWindows or Mac or Linuxで異なりますが、基本的にやることは同じです。
ただ、実行するコマンドが異なったり、バージョンでエラーが出ることは日常茶飯事です。

## 質問3
パッケージです。
```
github.com/gin-gonic/gin
```
のURLに飛んでみると、ginのソースコードが見れます。

## 質問4

Ginの裏側は理解しなくてOKです！
今は「こうやって使うんだ」くらいで全く問題ないです！

## 質問5

`Jsoniter`は自分も初めて見ました。
Ginは使っていますが、細かい仕様まで理解していないです...
